version: "3.7"

services:
  redis:
    image: redis:4
    ports:
      - 6379:6379
  worker:
    build: .
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - .:/code/server
    command: celery -A tasks worker -l info
  server:
    build: .
    depends_on:
      - worker
    ports:
      - 8000:8000
    volumes:
      - .:/code/server
